-- Week 11 - Supabase setup
-- Jalankan file ini di Supabase SQL Editor.

create table if not exists public.photo (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  latitude text,
  longitude text,
  image_url text
);

alter table public.photo enable row level security;

drop policy if exists "Allow public access photo" on public.photo;

create policy "Allow public access photo"
on public.photo
for all
to public
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Allow public access images bucket" on storage.objects;

create policy "Allow public access images bucket"
on storage.objects
for all
to public
using (bucket_id = 'images')
with check (bucket_id = 'images');
